### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by mileo** [OCA/iot#4]
Odoo server should have a broker process to handle mqtt requests.

**Comment by etobella** [comment]
Well, I have made a major change on the module in order to integrate AMQP support. I decided that it was a better choice because with rabbitmq I can transform to MQTT automatically. I am still working on it in order to make it easier. I hope I will make a functional PR soon (It involves several modules, so I need to think on it).

You can review the code on https://github.com/etobella/iot/tree/11.0-add-iot_put

**Comment by etobella** [comment]
Closing as there is already a PR for AMQP
